"use client";
import {useEffect,useMemo,useState} from 'react';
import type {GameSnapshot,PlayerStats,ServerEvent} from '@horii-overlay/protocol';
const API=process.env.NEXT_PUBLIC_API_URL??'';
const demo:GameSnapshot={gameId:'loading',mode:'BEDWARS_DOUBLES',status:'LOBBY',players:[],updatedAt:new Date().toISOString()};
function tone(v:number|undefined){return (v??0)>=5?'hot':(v??0)>=2?'warm':'neutral'}
export default function Home(){const [game,setGame]=useState(demo);const [state,setState]=useState('connecting');const [sort,setSort]=useState<keyof PlayerStats>('fkdr');const [query,setQuery]=useState('');const [session,setSession]=useState('');
 useEffect(()=>{const url=new URL(window.location.href);let id=url.searchParams.get('session')||sessionStorage.getItem('horii-overlay-session')||crypto.randomUUID();sessionStorage.setItem('horii-overlay-session',id);if(!url.searchParams.get('session')){url.searchParams.set('session',id);window.history.replaceState({},'',url.toString())}setSession(id)},[]);
 useEffect(()=>{if(!session)return;let ws:WebSocket|undefined;let retry=1000;let alive=true;const connect=()=>{ws=new WebSocket(`${API.replace(/^http/,'ws')}/api/stream?session=${encodeURIComponent(session)}`);ws.onopen=()=>{setState('live');retry=1000};ws.onmessage=e=>{const msg=JSON.parse(e.data) as ServerEvent;if(msg.type==='GAME_UPDATE')setGame(msg.data)};ws.onclose=()=>{if(alive){setState('reconnecting');setTimeout(connect,retry);retry=Math.min(retry*2,10000)}}};connect();return()=>{alive=false;ws?.close()}},[session]);
 const players=useMemo(()=>game.players.filter(p=>p.username.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(b[sort]??0)-Number(a[sort]??0)),[game.players,query,sort]);
 return <main><header><div className="brand"><span className="mark">H</span><div><h1>HORII OVERLAY</h1><p>LIVE HYPIXEL INTELLIGENCE</p></div></div><div className="status"><i className={state==='live'?'on':''}/> {state}</div></header><section className="hero"><div><span className="eyebrow">CURRENT GAME</span><h2>{game.mode.replaceAll('_',' ')}</h2><p className="muted">{game.status} · Updated {new Date(game.updatedAt).toLocaleTimeString()}</p></div><div className="count"><strong>{game.players.length}</strong><span>players tracked</span></div></section><section className="toolbar"><input placeholder="Search player" value={query} onChange={e=>setQuery(e.target.value)}/><label>Sort <select value={sort} onChange={e=>setSort(e.target.value as keyof PlayerStats)}><option value="fkdr">FKDR</option><option value="wlr">WLR</option><option value="wins">Wins</option><option value="level">Level</option><option value="finalKills">Final kills</option><option value="bedsBroken">Beds broken</option></select></label></section><section className="table"><div className="row heading"><span>PLAYER</span><span>FKDR</span><span>WLR</span><span>WINS</span><span>LEVEL</span><span>FINALS</span><span>BEDS</span></div>{players.map((p)=><div className="row" key={p.username}><span className="player"><b>{p.username}</b><small>#{p.uuid?.slice(0,6)??'live'}</small></span><span className={tone(p.fkdr)}>{p.fkdr?.toFixed(2)}</span><span>{p.wlr?.toFixed(2)}</span><span>{p.wins?.toLocaleString()}</span><span>{p.level}</span><span>{p.finalKills?.toLocaleString()}</span><span>{p.bedsBroken?.toLocaleString()}</span></div>)}{players.length===0&&<div className="empty">No players match your search.</div>}</section><footer><span>Horii Overlay · BedWars MVP</span><span>WebSocket {state}</span></footer></main>}
