buildscript { repositories { maven { url='https://maven.minecraftforge.net' }; mavenCentral() }; dependencies { classpath 'net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT' } }
apply plugin: 'net.minecraftforge.gradle.forge'
version='0.1.0'; group='dev.horii.overlay'
sourceCompatibility=JavaVersion.VERSION_1_8; targetCompatibility=JavaVersion.VERSION_1_8
 minecraft { version='1.8.9-11.15.1.2318-1.8.9'; runDir='run'; mappings='stable_22' }
repositories { mavenCentral() }
configurations { embedded }
dependencies {
 compile 'org.java-websocket:Java-WebSocket:1.5.6'
 embedded 'org.java-websocket:Java-WebSocket:1.5.6'
}
jar {
 exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
}
reobfJar.doLast {
 def outputJar = file("${buildDir}/libs/${project.name}-${version}.jar")
 configurations.embedded.each { dependency ->
  ant.zip(destfile: outputJar, update: true) {
   zipfileset(src: dependency) {
    exclude(name: 'META-INF/*.SF')
    exclude(name: 'META-INF/*.DSA')
    exclude(name: 'META-INF/*.RSA')
   exclude(name: 'META-INF/versions/**')
   }
  }
 }
}
processResources { inputs.property 'version', project.version; filesMatching('mcmod.info'){ expand 'version':project.version } }
