import Fastify from 'fastify';
import cors from '@fastify/cors';
import websocket from '@fastify/websocket';
import { ClientEventSchema, ServerEvent, GameSnapshot, PlayerStats } from '@horii-overlay/protocol';

const now=()=>new Date().toISOString();
type SessionState={snapshot:GameSnapshot|null;clients:Set<any>;apiKey?:string;username?:string};
const sessions=new Map<string,SessionState>();
const validSession=(value:unknown)=>{const id=String(value??'').trim();return /^[a-zA-Z0-9_-]{8,128}$/.test(id)?id:'demo';};
const getSession=(id:string):SessionState=>{let state=sessions.get(id);if(!state){state={snapshot:null,clients:new Set()};sessions.set(id,state);}return state;};
function number(v:unknown){return typeof v==='number'&&Number.isFinite(v)?Math.max(0,v):0;}
function mapPlayer(username:string,p:any):PlayerStats{const s=p?.stats?.Bedwars??{};const fk=number(s.final_kills_bedwars),fd=number(s.final_deaths_bedwars),w=number(s.wins_bedwars),l=number(s.losses_bedwars);return {username,uuid:typeof p?.uuid==='string'?p.uuid:undefined,level:number(p?.achievements?.bedwars_level),fkdr:fd?fk/fd:fk,wlr:l?w/l:w,wins:w,losses:l,kills:number(s.kills_bedwars),deaths:number(s.deaths_bedwars),finalKills:fk,finalDeaths:fd,bedsBroken:number(s.beds_broken_bedwars)};}
async function loadHypixel(key:string,username:string){const response=await fetch(`https://api.hypixel.net/v2/player?key=${encodeURIComponent(key)}&name=${encodeURIComponent(username)}`);const data=await response.json() as any;if(!response.ok||data.success!==true)throw new Error(data.cause||'Hypixel API request failed');if(!data.player)throw new Error('Player was not found by Hypixel');return mapPlayer(username,data.player);}
function broadcast(state:SessionState){if(!state.snapshot)return;const event={type:'GAME_UPDATE',data:state.snapshot} as ServerEvent;for(const client of state.clients)if(client.readyState===1)client.send(JSON.stringify(event));}
async function fetchPlayers(state:SessionState,names:string[]){const unique=[...new Set(names.map(x=>x.trim()).filter(x=>/^[A-Za-z0-9_]{1,16}$/.test(x)))].slice(0,32);if(!state.apiKey||!unique.length)return [];const results=await Promise.all(unique.map(async name=>{try{return await loadHypixel(state.apiKey!,name);}catch{return null;}}));return results.filter((x):x is PlayerStats=>x!==null);}
export async function buildServer(){
 const app=Fastify({logger:false});await app.register(cors,{origin:true});await app.register(websocket);
 app.get('/health',async()=>({ok:true,service:'horii-overlay-api',time:now()}));
 app.get('/api/game/current',async(req:any,reply:any)=>{const state=getSession(validSession(req.query?.session));if(!state.snapshot)return reply.code(404).send({configured:false,message:'Configure your Hypixel API key and username first'});return state.snapshot;});
 app.post('/api/session/config',async(req:any,reply:any)=>{const body=req.body as any;const sessionId=validSession(body?.sessionId);const apiKey=String(body?.apiKey??'').trim();const username=String(body?.username??'').trim();if(apiKey.length<20||apiKey.length>200)return reply.code(400).send({error:'Enter a valid Hypixel API key'});if(!/^[A-Za-z0-9_]{1,16}$/.test(username))return reply.code(400).send({error:'Enter a valid Minecraft username'});try{const player=await loadHypixel(apiKey,username);const state=getSession(sessionId);state.apiKey=apiKey;state.username=username;state.snapshot={gameId:`${sessionId}-lobby`,mode:'UNKNOWN',status:'LOBBY',players:[player],updatedAt:now()};broadcast(state);return {ok:true,username:player.username};}catch(error){return reply.code(400).send({error:error instanceof Error?error.message:'Hypixel validation failed'});}});
 const bridgeHandler=(socket:any,req:any)=>{const sessionId=validSession(req.query?.session);const state=getSession(sessionId);const expected=process.env.WS_SHARED_SECRET;const supplied=String(req.query?.token??'');if(expected&&supplied!==expected){socket.close(1008,'unauthorized');return;}state.clients.add(socket);const send=(event:ServerEvent)=>socket.send(JSON.stringify(event));send({type:'CONNECTION_STATE',data:{state:'connected'}});if(state.snapshot)send({type:'GAME_UPDATE',data:state.snapshot});socket.on('message',async(raw:Buffer)=>{let body:unknown;try{body=JSON.parse(raw.toString());}catch{send({type:'ERROR',data:{code:'INVALID_JSON',message:'Message must be valid JSON'}});return;}const parsed=ClientEventSchema.safeParse(body);if(!parsed.success){send({type:'ERROR',data:{code:'INVALID_EVENT',message:'Invalid client event'}});return;}if(parsed.data.type==='GAME_START'){const players=await fetchPlayers(state,parsed.data.data.players.map(p=>p.username));if(players.length){state.snapshot={gameId:`${sessionId}-${Date.now()}`,mode:parsed.data.data.mode,status:'IN_GAME',players,updatedAt:now()};broadcast(state);}}});socket.on('close',()=>state.clients.delete(socket));};
 app.get('/api/stream',{websocket:true},(socket:any,req:any)=>bridgeHandler(socket,req));app.get('/api/bridge',{websocket:true},(socket:any,req:any)=>bridgeHandler(socket,req));
 const timer=setInterval(()=>{for(const state of sessions.values())if(state.snapshot){state.snapshot={...state.snapshot,updatedAt:now()};broadcast(state);}},15000);app.addHook('onClose',async()=>clearInterval(timer));return app;
}
